# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 05:09
from __future__ import unicode_literals

import cats.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важная новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='y_pos',
            field=models.IntegerField(blank=True, default=50, validators=[cats.validators.background_y_position_validator], verbose_name='Позиция по вертикали'),
        ),
    ]
