# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='subject',
        ),
        migrations.AddField(
            model_name='news',
            name='vk_album_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID новости в VK'),
        ),
        migrations.DeleteModel(
            name='NewsSubject',
        ),
    ]
