# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 09:12
from __future__ import unicode_literals

import cats.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171215_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='use_background',
            field=models.BooleanField(default=True, verbose_name='use_background'),
        ),
        migrations.AddField(
            model_name='article',
            name='y_pos',
            field=models.IntegerField(blank=True, default=50, validators=[cats.validators.background_y_position_validator], verbose_name='Позиция по вертикали'),
        ),
        migrations.AddField(
            model_name='news',
            name='use_background',
            field=models.BooleanField(default=True, verbose_name='use_background'),
        ),
    ]
