# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171205_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать тему статей'),
        ),
    ]
