# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20171219_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='use_background',
            field=models.BooleanField(default=True, verbose_name='Использовать изображение для фона страницы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='use_background',
            field=models.BooleanField(default=True, verbose_name='Использовать изображение для фона страницы'),
        ),
    ]
