# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171219_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Изображение для превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Изображение для превью'),
        ),
    ]
