# Generated by Django 2.2 on 2020-02-08 10:02

import cats.validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200125_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Партнер')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание партнера')),
                ('image', models.URLField(verbose_name='Лого партнера')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название партнерского мероприятия')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Статья об отчетном партнерском мероприятии')),
                ('date', models.DateTimeField(verbose_name='Время проведения мероприятия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.URLField(verbose_name='Главное фото мероприятия')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('y_pos', models.IntegerField(blank=True, default=50, validators=[cats.validators.background_y_position_validator], verbose_name='Позиция фонового изобажения по вертикали')),
                ('use_background', models.BooleanField(default=True, verbose_name='Использовать изображение для фона страницы')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Партнерское мероприятие',
                'verbose_name_plural': 'Партнерские мероприятия',
            },
        ),
    ]
