# Generated by Django 2.2 on 2020-08-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на партнера'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Краткое описание партнера'),
        ),
    ]
