version: '3'

services:
    postgres:
        image: postgres:11.2
        container_name: "catsekb.ru-postgres"
        restart: always
        volumes:
            - /srv/catsekb.ru/postgres:/var/lib/postgresql/data
        networks:
            - internal
        environment:
            POSTGRES_NAME: catsekb
            POSTGRES_USER: catsekb
            POSTGRES_PASSWORD: db_key_txt
    django:
        image: catsekb.ru:latest
        container_name: catsekb.ru
        restart: always
        volumes:
            - /srv/catsekb.ru/:/srv/
        depends_on:
            - postgres
        networks:
            - internal
    nginx:
        image: nginx:1.17
        restart: always
        volumes:
            - /srv/catsekb.ru/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - /srv/catsekb.ru/static:/srv/static
            - /srv/catsekb.ru/certs:/etc/letsencrypt
            - /srv/catsekb.ru/certs-data:/data/letsencrypt
        networks:
            - internal
            - default
        ports:
            - "80:80"
            - "443:443"

networks:
    internal:
