"""
Django settings for catsekb project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import join

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

with open(os.path.join(os.sep, 'srv', 'vk_token.txt')) as f:
        VK_TOKEN = f.read().strip()
# SECURITY WARNING: keep the secret key used in production secret!
try:
    with open(os.path.join(os.sep, 'srv', 'secret_key.txt')) as f:
        SECRET_KEY = f.read().strip()
except FileNotFoundError:
    SECRET_KEY = '1j(lfw54!y!f3u%&8%e*(m)@k=p&@2iphm53p$$li&8hy#@gwl'
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1']
else:
    DEBUG = False
    ALLOWED_HOSTS = ['xn--80aegc1blqbj1c4c.xn--p1ai', 'www.xn--80aegc1blqbj1c4c.xn--p1ai']

# Application definition

INSTALLED_APPS = [
    'catsekb_page.apps.CatsekbPageConfig',
    'huskyekb_page.apps.HuskyekbPageConfig',
    'rotvodom_page.apps.RotvodomPageConfig',
    'cats.apps.CatsConfig',
    'articles.apps.ArticlesConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #  WYSIWYG editor
    'ckeditor',
    #  For store single objects in DB
    'constance',
    'constance.backends.database',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catsekb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catsekb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
try:
    with open(os.path.join(os.sep, 'srv', 'db_key.txt')) as f:
        db_key = f.read().strip()
except FileNotFoundError:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'catsekb',
            'USER': 'catsekb',
            'PASSWORD': db_key,
            'HOST': 'postgres',
            'PORT': '5432',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Yekaterinburg'  # TODO: set timezone

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.sep, 'srv', 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_ADDITIONAL_FIELDS = {
    'editable_content': ['ckeditor.fields.RichTextFormField', {}],
}

CONSTANCE_CONFIG = {
    'CONTACTS_PAGE_CONTENT': (
        """<p>
            Instagram:&nbsp;<a href="https://www.instagram.com/catsekb/" target="_blank">https://www.instagram.com/catsekb/</a><br />
            ВКонтакте:&nbsp;<a href="https://vk.com/catsekb_vk" target="_blank">https://vk.com/catsekb_vk</a><br />
            Facebook:&nbsp;<a href="https://www.facebook.com/cats.ekb" target="_blank">https://www.facebook.com/cats.ekb</a><br />
            Одноклассники:&nbsp;<a href="https://ok.ru/catsekb" target="_blank">https://ok.ru/catsekb</a><br />
            Email: сatsekb@gmail.com<br />
        </p>""",
        'Тут необходимо указать текст, который будет отображаться на странице "Контакты"',
        'editable_content'
    ),
    'HELP_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Помощь приюту"',
        'editable_content'
    ),
    'ABOUT_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "О проекте"',
        'editable_content'
    ),
    'NEEDS_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Нужды приюта"',
        'editable_content'
    ),
    'DOCUMENTS_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Документы"',
        'editable_content'
    ),
    'REPORTS_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Отчетность"',
        'editable_content'
    ),
    'MEDIA_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Сми о нас"',
        'editable_content'
    ),
    'GET_ANIMAL_GUIDE_PAGE_CONTENT': (
        "Эта страница еще в разработке",
        'Тут необходимо указать текст, который будет отображаться на странице "Взять животное из приюта"',
        'editable_content'
    ),
    'CATS_COUNT_CORRECTION': (
        0,
        'Коррекция числа пристроенных котов'
    ),
    'HUSKY_COUNT_CORRECTION': (
        0,
        'Коррекция числа пристроенных хаски'
    ),
    'ROTTWEILER_COUNT_CORRECTION': (
        0,
        'Коррекция числа пристроенных ротвейлеров'
    )
}


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
