from django import forms

from articles.article_constants import NEWS_TITLE, NEWS_TEXT, NEWS_CREATED, NEWS_SHOW, \
    NEWS_IMPORTANT, NEWS_Y_POS, NEWS_AUTHOR, NEWS_KEY_TITLE_HELP_TEXT, NEWS_KEY_TEXT_HELP_TEXT, \
    NEWS_KEY_CREATED_HELP_TEXT, NEWS_KEY_SHOW_HELP_TEXT, NEWS_KEY_IMPORTANT_HELP_TEXT, NEWS_KEY_Y_POS_HELP_TEXT, \
    NEWS_KEY_AUTHOR_HELP_TEXT, ARTICLE_TITLE, ARTICLE_TEXT, ARTICLE_CREATED, ARTICLE_SHOW, ARTICLE_AUTHOR, \
    ARTICLE_SUBJECT, ARTICLE_Y_POS, ARTICLE_USE_BACKGROUND, ARTICLE_KEY_TITLE_HELP_TEXT, ARTICLE_KEY_TEXT_HELP_TEXT, \
    ARTICLE_KEY_CREATED_HELP_TEXT, ARTICLE_KEY_SHOW_HELP_TEXT, ARTICLE_KEY_AUTHOR_HELP_TEXT, \
    ARTICLE_KEY_SUBJECT_HELP_TEXT, ARTICLE_KEY_Y_POS_HELP_TEXT
from articles.models import News, Article
from catsekb.constants import IMAGE, IMAGE_KEY_HELP_TEXT


class NewsForm(forms.ModelForm):
    model = News
    fields = (
        NEWS_TITLE,
        NEWS_TEXT,
        NEWS_CREATED,
        NEWS_SHOW,
        NEWS_IMPORTANT,
        NEWS_Y_POS,
        NEWS_AUTHOR,
    )

    help_text = {
        NEWS_TITLE: NEWS_KEY_TITLE_HELP_TEXT,
        NEWS_TEXT: NEWS_KEY_TEXT_HELP_TEXT,
        NEWS_CREATED: NEWS_KEY_CREATED_HELP_TEXT,
        NEWS_SHOW: NEWS_KEY_SHOW_HELP_TEXT,
        NEWS_IMPORTANT: NEWS_KEY_IMPORTANT_HELP_TEXT,
        NEWS_Y_POS: NEWS_KEY_Y_POS_HELP_TEXT,
        NEWS_AUTHOR: NEWS_KEY_AUTHOR_HELP_TEXT,
        IMAGE: IMAGE_KEY_HELP_TEXT,
    }


class ArticleForm(forms.ModelForm):
    model = Article
    fields = (
        ARTICLE_TITLE,
        ARTICLE_TEXT,
        ARTICLE_CREATED,
        ARTICLE_SHOW,
        ARTICLE_AUTHOR,
        ARTICLE_SUBJECT,
        IMAGE,
        ARTICLE_Y_POS,
        ARTICLE_USE_BACKGROUND,
    )

    help_text = {
        ARTICLE_TITLE: ARTICLE_KEY_TITLE_HELP_TEXT,
        ARTICLE_TEXT: ARTICLE_KEY_TEXT_HELP_TEXT,
        ARTICLE_CREATED: ARTICLE_KEY_CREATED_HELP_TEXT,
        ARTICLE_SHOW: ARTICLE_KEY_SHOW_HELP_TEXT,
        ARTICLE_AUTHOR: ARTICLE_KEY_AUTHOR_HELP_TEXT,
        ARTICLE_SUBJECT: ARTICLE_KEY_SUBJECT_HELP_TEXT,
        IMAGE: IMAGE_KEY_HELP_TEXT,
        ARTICLE_Y_POS: ARTICLE_KEY_Y_POS_HELP_TEXT,
        ARTICLE_USE_BACKGROUND: ARTICLE_KEY_Y_POS_HELP_TEXT,
    }

