# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, unique=True, verbose_name='Имя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_of_birth', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='AnimalDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('animal', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cats.Animal')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50, verbose_name='alt')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('width', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, default=None, null=True, verbose_name='Высота')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cats.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, default=None, max_length=32, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип особенности',
                'verbose_name_plural': 'Типы особенностей',
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Значение (текст)')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.FieldType')),
            ],
            options={
                'verbose_name': 'Значение особенности',
                'verbose_name_plural': 'Значения особенностей',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='field_value',
            field=models.ManyToManyField(blank=True, default=None, to='cats.FieldValue', verbose_name='Значение особенности'),
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.Group', verbose_name='Группа'),
        ),
    ]
