# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32, verbose_name='Имя')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол')),
                ('birthday_precision', models.CharField(choices=[('Y', 'до года'), ('M', 'до месяца'), ('D', 'до дня')], default='', max_length=1, null=True, verbose_name='Точность даты рождения')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True, verbose_name='День рождения')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать котика')),
                ('location_status', models.CharField(blank=True, choices=[('H', 'Пристроен'), ('S', 'В приюте'), ('D', 'На радуге')], default='', max_length=1, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default=None, verbose_name='URL изображения')),
                ('alt', models.CharField(max_length=50, verbose_name='Подпись к фото')),
                ('width', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, default=None, null=True, verbose_name='Высота')),
                ('favourite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Animal')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, default=None, max_length=32, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип особенности',
                'verbose_name_plural': 'Типы особенностей',
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Особенность')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.FieldType')),
            ],
            options={
                'verbose_name': 'Характерная особенность',
                'verbose_name_plural': 'Значения особенностей',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать группу')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='field_value',
            field=models.ManyToManyField(blank=True, default=None, to='cats.FieldValue', verbose_name='Характерная особенность'),
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.Group', verbose_name='Группа'),
        ),
    ]
