# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'verbose_name': 'Тип особенности', 'verbose_name_plural': 'Типы особенностей'},
        ),
        migrations.RemoveField(
            model_name='animaldescription',
            name='fields',
        ),
        migrations.AddField(
            model_name='animal',
            name='field_value',
            field=models.ManyToManyField(to='cats.FieldValue', verbose_name='Значение особенности'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='animaldescription',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cats.Animal'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cats.Animal'),
        ),
    ]
