# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='background',
            field=models.BooleanField(default=False, verbose_name='Использовать в качестве фона'),
        ),
    ]
