# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(default=None, null=True, verbose_name='День рождения'),
        ),
    ]
