# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20171004_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя'),
        ),
    ]
