# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20170912_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
