# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Редактирование хештега'),
        ),
        migrations.AlterField(
            model_name='animalimage',
            name='image_url',
            field=models.URLField(default=None, verbose_name='URL изображения'),
        ),
    ]
