# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20170902_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ширина'),
        ),
    ]
