# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_animal_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birthday_precision',
            field=models.CharField(choices=[('Y', 'до года'), ('M', 'до месяца'), ('D', 'до дня')], default=None, max_length=1, null=True, verbose_name='Точность даты рождения'),
        ),
    ]
