# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20170902_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='field_value',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cats.FieldValue', verbose_name='Значение особенности'),
        ),
    ]
