# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20170912_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
    ]
