# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20170912_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Возраст'),
        ),
    ]
