# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20171103_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image_url',
            field=models.ImageField(default=None, upload_to='', verbose_name='URL изображения'),
        ),
    ]
