# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20171004_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default=None, max_length=1, verbose_name='Пол'),
        ),
    ]
