# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20170912_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(blank=True, default=None, verbose_name='Лет')),
                ('months', models.IntegerField(blank=True, default=None, verbose_name='Месяцев')),
                ('days', models.IntegerField(blank=True, default=None, verbose_name='Дней')),
                ('animal', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cats.Animal')),
            ],
        ),
    ]
