# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20171004_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldvalue',
            options={'verbose_name': 'Характерная особенность', 'verbose_name_plural': 'Значения особенностей'},
        ),
        migrations.AddField(
            model_name='animal',
            name='location_status',
            field=models.CharField(choices=[('H', 'Дома'), ('S', 'В приюте')], default='S', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birthday_precision',
            field=models.CharField(choices=[('Y', 'до года'), ('M', 'до месяца'), ('D', 'до дня')], default='', max_length=1, null=True, verbose_name='Точность даты рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='field_value',
            field=models.ManyToManyField(blank=True, default=None, to='cats.FieldValue', verbose_name='Характерная особенность'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='value_text',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Особенность'),
        ),
    ]
