# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20171108_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image_url',
            field=models.URLField(default=None, verbose_name='URL изображения'),
        ),
    ]
