# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_animalage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalage',
            options={'verbose_name': 'Возраст', 'verbose_name_plural': 'Возраст'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='date_of_birth',
        ),
    ]
