# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20171117_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='В приюте'),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='created',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата публикации'),
        ),
    ]
