# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20171117_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='valid_info',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
