# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_auto_20171129_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
