# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location_status',
            field=models.CharField(blank=True, choices=[('H', 'Пристроен'), ('S', 'В поиске дома'), ('D', 'На радуге')], default='', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
