# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0016_auto_20171219_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео Youtube')),
                ('description', models.TextField(verbose_name='Описание видео')),
            ],
            options={
                'verbose_name_plural': 'Видео',
                'verbose_name': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.AnimalVideo', verbose_name='Видео'),
        ),
    ]
