# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_auto_20180201_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalvideo',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать видео'),
        ),
    ]
