# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0018_animalvideo_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalvideo',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Название видео'),
        ),
    ]
