# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0019_auto_20180202_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalvideo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
