# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-08-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0021_auto_20180202_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalvideo',
            name='put_to_index_page',
            field=models.BooleanField(default=False, verbose_name='Поместить на стартовую'),
        ),
    ]
