# Generated by Django 2.2 on 2020-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0022_auto_20190803_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='valid_info',
        ),
        migrations.AddField(
            model_name='animal',
            name='project',
            field=models.CharField(choices=[('catsekb', 'CatsEkb'), ('huskyekb', 'HuskyEkb'), ('rotvodom', 'Rotvodom')], default='catsekb', max_length=10, verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
