# Generated by Django 2.2 on 2020-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0023_auto_20200126_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vk_group_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Id группы VK'),
        ),
    ]
