# Generated by Django 2.2 on 2020-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0024_animal_vk_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='location_status',
            field=models.CharField(choices=[('H', 'Пристроен'), ('S', 'В поиске дома'), ('D', 'На радуге')], max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать питомца'),
        ),
    ]
